### ISSUE TITLE
Problems parsing KCQL with numeric digits in target name with version 2.2

### ISSUE THREAD

**Issue by joewood** [Landoop/kafka-connect-query-language#22]
I'm using the 0.3.0 version of the JMS Source Connector, which uses 0.9.0 of Common and 2.2 of KCQL.  For the following string the KCQL parser is complaining that the `WITHTYPE` is missing:

```
INSERT INTO bci-tester-topic-mq SELECT * FROM D.TS.TSF.OUT.9931.2.COPY WITHTYPE QUEUE
```

Error reported as:
```
 WITHTYPE not set for kcql com.datamountaineer.kcql.Kcql@3409f81d so can't determine JMS destination type. Provide WITHTYPE=TOPIC or WITHTYPE=QUEUE
at com.datamountaineer.streamreactor.connect.jms.config.JMSSettings$$anonfun$apply$2.apply(JMSSettings.scala:127)\n\tat com.datamountaineer.streamreactor.connect.jms.config.JMSSettings$$anonfun$apply$2.apply(JMSSettings.scala:125)\n\tat scala.collection.immutable.Set$Set1.foreach(Set.scala:94)\n\tat com.datamountaineer.streamreactor.connect.jms.config.JMSSettings$.apply(JMSSettings.scala:125)\n\tat com.datamountaineer.streamreactor.connect.jms.source.JMSSourceTask.start(JMSSourceTask.scala:44)
at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:142)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n
```

If I remove the numbers it works fine:
```
INSERT INTO bci-tester-topic-mq SELECT * FROM D.TS.TSF.OUT.COPY WITHTYPE QUEUE
```

Looking at the [antl](https://github.com/Landoop/kafka-connect-query-language/blob/master/src/main/antlr/ConnectorLexer.g4#L180) parsing syntax it seems that the parser should be OK with numerics. But I'm not sure if this repo has version 2.2 as the `WITHTYPE` clause seems to be missing. Is this version checked into Github?

**Comment by stheppi** [comment]
@joewood 
This is actually coming from the `FROM` section.
Please change the query to :

```INSERT INTO bci-tester-topic-mq SELECT * FROM `D.TS.TSF.OUT.9931.2.COPY` WITHTYPE QUEUE```.

**Comment by joewood** [comment]
Yes, just got that. Thanks - found the new syntax in the 2.0 branch. Looks like the `.` needs to be escaped. Thanks.
