### ISSUE TITLE
Error if target contains reserved word

### ISSUE THREAD

**Issue by CrystalMethod** [Landoop/kafka-connect-query-language#36]
```
INSERT INTO batch SELECT * FROM /foo
INSERT INTO com.edge.batch SELECT * FROM /foo
INSERT INTO com.edge.batch.start SELECT * FROM /foo
```
```
Exception in thread "main" java.lang.IllegalArgumentException: Invalid syntax.failed to parse at line 1 due to mismatched input 'batch' expecting {'.', FIELD, TOPICNAME}
	at com.datamountaineer.kcql.Kcql.parse(Kcql.java:897)
...
Caused by: java.lang.IllegalStateException: failed to parse at line 1 due to mismatched input 'batch' expecting {'.', FIELD, TOPICNAME}
	at com.datamountaineer.kcql.Kcql$1.syntaxError(Kcql.java:403)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:299)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:124)
	at com.datamountaineer.kcql.antlr4.ConnectorParser.table_name(ConnectorParser.java:1561)
	at com.datamountaineer.kcql.antlr4.ConnectorParser.insert_from_clause(ConnectorParser.java:702)
	at com.datamountaineer.kcql.antlr4.ConnectorParser.stat(ConnectorParser.java:207)
	at com.datamountaineer.kcql.Kcql.parse(Kcql.java:895)
	... 1 more
Caused by: org.antlr.v4.runtime.InputMismatchException
	at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:242)
	at com.datamountaineer.kcql.antlr4.ConnectorParser.table_name(ConnectorParser.java:1536)
	... 4 more
```
working samples:
```
INSERT INTO barbatch SELECT * FROM /foo
INSERT INTO com.edge.batchstart SELECT * FROM /foo
INSERT INTO com.edge.batch_start SELECT * FROM /foo
INSERT INTO /batch SELECT * FROM foo
```

**Comment by stheppi** [comment]
Hi @CrystalMethod,
 You should escape the topic. Any db requires escaping. In this case:
```
INSERT INTO `com.edge.batch.start` SELECT * FROM 
```

**Comment by CrystalMethod** [comment]
Sometimes it's that simple. Thx.
